-- phpMyAdmin SQL Dump
-- version 5.1.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Dec 05, 2024 at 01:54 AM
-- Server version: 8.0.36-28
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dbqmnddu2ryxr8`
--

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `id` int NOT NULL,
  `order_date` datetime NOT NULL,
  `total` decimal(10,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `author` varchar(255) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `description` text NOT NULL,
  `image_url` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `author`, `price`, `description`, `image_url`) VALUES
(58, 'A Game of Thrones', 'George R. R. Martin', '11.99', 'Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister forces are massing beyond the kingdom\'s protective Wall. To the south, the king\'s powers are failing—his most trusted adviser dead under mysterious circumstances and his enemies emerging from the shadows of the throne. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the frozen land they were born to. Now Lord Eddard Stark is reluctantly summoned to serve as the king\'s new Hand, an appointment that threatens to sunder not only his family but the kingdom itself. Sweeping from a harsh land of cold to a summertime kingdom of epicurean plenty, A Game of Thrones tells a tale of lords and ladies, soldiers and sorcerers, assassins and bastards, who come together in a time of grim omens. Here an enigmatic band of warriors bear swords of no human metal; a tribe of fierce wildlings carry men off into madness; a cruel young dragon prince barters his sister to win back his throne; a child is lost in the twilight between life and death; and a determined woman undertakes a treacherous journey to protect all she holds dear. Amid plots and counter-plots, tragedy and betrayal, victory and terror, allies and enemies, the fate of the Starks hangs perilously in the balance, as each side endeavors to win that deadliest of conflicts: the game of thrones.', 'images/game_of_thrones.jpg'),
(59, 'A Clash of Kings', 'George R. R. Martin', '12.99', 'A comet the color of blood and flame cuts across the sky. Two great leaders—Lord Eddard Stark and Robert Baratheon—who hold sway over an age of enforced peace are dead, victims of royal treachery. Now, from the ancient citadel of Dragonstone to the forbidding shores of Winterfell, chaos reigns. Six factions struggle for control of a divided land and the Iron Throne of the Seven Kingdoms, preparing to stake their claims through tempest, turmoil, and war. It is a tale in which brother plots against brother and the dead rise to walk in the night. Here a princess masquerades as an orphan boy; a knight of the mind prepares a poison for a treacherous sorceress; and wild men descend from the Mountains of the Moon to ravage the countryside. Against a backdrop of incest and fratricide, alchemy and murder, victory may go to the men and women possessed of the coldest steel...and the coldest hearts. For when kings clash, the whole land trembles. Here is the second volume in George R.R. Martin magnificent cycle of novels that includes A Game of Thrones and A Storm of Swords. As a whole, this series comprises a genuine masterpiece of modern fantasy, bringing together the best the genre has to offer. Magic, mystery, intrigue, romance, and adventure fill these pages and transport us to a world unlike any we have ever experienced. Already hailed as a classic, George R.R. Martin stunning series is destined to stand as one of the great achievements of imaginative fiction.', 'images/clash_of_kings.jpg'),
(60, 'A Storm of Swords', 'George R. R. Martin', '12.99', 'Here is the third volume in George R.R. Martin\'s magnificent cycle of novels that includes A Game of Thrones and A Clash of Kings. Together, this series comprises a genuine masterpiece of modern fantasy, destined to stand as one of the great achievements of imaginative fiction. Of the five contenders for power, one is dead, another in disfavor, and still the wars rage as alliances are made and broken. Joffrey sits on the Iron Throne, the uneasy ruler of the Seven Kingdoms. His most bitter rival, Lord Stannis, stands defeated and disgraced, victim of the sorceress who holds him in her thrall. Young Robb still rules the North from the fortress of Riverrun. Meanwhile, making her way across a blood-drenched continent is the exiled queen, Daenerys, mistress of the only three dragons still left in the world. And as opposing forces manoeuver for the final showdown, an army of barbaric wildlings arrives from the outermost limits of civilization, accompanied by a horde of mythical Others—a supernatural army of the living dead whose animated corpses are unstoppable. As the future of the land hangs in the balance, no one will rest until the Seven Kingdoms have exploded in a veritable storm of swords...', 'images/storm_of_swords.jpg'),
(61, 'A Feast for Crows', 'George R. R. Martin', '12.99', 'Bloodthirsty, treacherous and cunning, the Lannisters are in power on the Iron Throne in the name of the boy-king Tommen. The war in the Seven Kingdoms has burned itself out, but in its bitter aftermath new conflicts spark to life. The Martells of Dorne and the Starks of Winterfell seek vengeance for their dead. Euron Crow\'s Eye, as black a pirate as ever raised a sail, returns from the smoking ruins of Valyria to claim the Iron Isles. From the icy north, where Others threaten the Wall, apprentice Maester Samwell Tarly brings a mysterious babe in arms to the Citadel.', 'images/feast_for_crows.jpg'),
(62, 'A Dance with Dragons', 'George R. R. Martin', '14.99', 'In the aftermath of a colossal battle, the future of the Seven Kingdoms hangs in the balance—beset by newly emerging threats from every direction. In the east, Daenerys Targaryen, the last scion of House Targaryen, rules with her three dragons as queen of a city built on dust and death. But Daenerys has thousands of enemies, and many have set out to find her. As they gather, one young man embarks upon his own quest for the queen, with an entirely different goal in mind. Fleeing from Westeros with a price on his head, Tyrion Lannister, too, is making his way to Daenerys. But his newest allies in this quest are not the rag-tag band they seem, and at their heart lies one who could undo Daenerys\'s claim to Westeros forever. Meanwhile, to the north lies the mammoth Wall of ice and stone—a structure only as strong as those guarding it. There, Jon Snow, 998th Lord Commander of the Night\'s Watch, will face his greatest challenge. For he has powerful foes not only within the Watch but also beyond, in the land of the creatures of ice. From all corners, bitter conflicts reignite, intimate betrayals are perpetrated, and a grand cast of outlaws and priests, soldiers and skinchangers, nobles and slaves, will face seemingly insurmountable obstacles. Some will fail, others will grow in the strength of darkness. But in a time of rising restlessness, the tides of destiny and politics will lead inevitably to the greatest dance of all.', 'images/dance_with_dragons.jpg'),
(63, 'Hyperion', 'Dan Simmons', '9.99', 'On the world called Hyperion, beyond the law of the Hegemony of Man, there waits the creature called the Shrike. There are those who worship it. There are those who fear it. And there are those who have vowed to destroy it. In the Valley of the Time Tombs, where huge, brooding structures move backward through time, the Shrike waits for them all. On the eve of Armageddon, with the entire galaxy at war, seven pilgrims set forth on a final voyage to Hyperion seeking the answers to the unsolved riddles of their lives. Each carries a desperate hope—and a terrible secret. And one may hold the fate of humanity in his hands.', 'images/hyperion.jpg'),
(64, 'The Fall of Hyperion', 'Dan Simmons', '9.99', 'In the stunning continuation of the epic adventure begun in Hyperion, Simmons returns us to a far future resplendent with drama and invention. On the world of Hyperion, the mysterious Time Tombs are opening. And the secrets they contain mean that nothing--nothing anywhere in the universe--will ever be the same.', 'images/fall_of_hyperion.jpg'),
(65, 'Endymion', 'Dan Simmons', '10.99', 'The multiple-award-winning SF master returns to the universe that is his greatest success--the world of Hyperion and The Fall of Hyperion--to tell a story of love and memory, triumph and terror in a novel even more magnificent than its predecessors. Two hundred and seventy-four years after the fall of the WorldWeb in Fall of Hyperion, Raoul Endymion is sent on a quest. Retrieving Aenea from the Sphinx before the Church troops reach her is only the beginning. With help from a blue-skinned android named A. Bettik, Raoul and Aenea travel the river Tethys, pursued by Father Captain Frederico DeSoya, an influential warrior-priest and his troops. The shrike continues to make enigmatic appearances, and while many questions were raised in Hyperion and Fall of Hyperion, still more are raised here. Raoul\'s quest will continue.', 'images/endymion.jpg'),
(66, 'The Rise of Endymion', 'Dan Simmons', '10.99', 'The time of reckoning has arrived. As a final genocidal Crusade threatens to enslave humanity forever, a new messiah has come of age. She is Aenea and she has undergone a strange apprenticeship to those known as the Others. Now her protector, Raul Endymion, one-time shepherd and convicted murderer, must help her deliver her startling message to her growing army of disciples. But first they must embark on a final spectacular mission to discover the underlying meaning of the universe itself. They have been followed on their journey by the mysterious Shrike--monster, angel, killing machine--who is about to reveal the long-held secret of its origin and purpose. And on the planet of Hyperion, where the story first began, the final revelation will be delivered--an apocalyptic message that unlocks the secrets of existence and the fate of humankind in the galaxy.', 'images/rise_of_endymion.jpg'),
(67, 'The Fellowship of the Ring', 'J. R. R. Tolkien', '8.99', 'One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them. In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.', 'images/fellowship_of_the_ring.jpg'),
(68, 'The Two Towers', 'J. R. R. Tolkien', '8.99', 'One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them. Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go.', 'images/two_towers.jpg'),
(69, 'The Return of the King', 'J. R. R. Tolkien', '8.99', 'One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them. The Dark Lord has risen, and as he unleashes hordes of Orcs to conquer all Middle-earth, Frodo and Sam struggle deep into his realm in Mordor. To defeat Sauron, the One Ring must be destroyed in the fires of Mount Doom. But the way is impossibly hard, and Frodo is weakening. The Ring corrupts all who bear it and Frodo\'s time is running out.', 'images/return_of_the_king.jpg'),
(70, 'Dune', 'Frank Herbert', '14.99', 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for... When House Atreides is betrayed, the destruction of Paul\'s family will set the boy on a journey toward a destiny greater than he could ever have imagined. And as he evolves into the mysterious man known as Muad\'Dib, he will bring to fruition humankind\'s most ancient and unattainable dream.', 'images/dune.jpg'),
(71, 'Dune Messiah', 'Frank Herbert', '12.99', 'Dune Messiah continues the story of Paul Atreides, better known--and feared--as the man christened Muad\'Dib. As Emperor of the Known Universe, he possesses more power than a single man was ever meant to wield. Worshipped as a religious icon by the fanatical Fremens, Paul faces the enmity of the political houses he displaced when he assumed the throne--and a conspiracy conducted within his own sphere of influence. And even as House Atreides begins to crumble around him from the machinations of his enemies, the true threat to Paul comes to his lover, Chani, and the unborn heir to his family\'s dynasty...', 'images/dune_messiah.jpg'),
(72, 'Children of Dune', 'Frank Herbert', '11.99', 'Book three in Frank Herbert\'s magnificent Dune Chronicles--one of the most significant sagas in the history of literary science fiction. The Children of Dune are twin siblings Leto and Ghanima Atreides, whose father, the Emperor Paul Muad\'Dib, disappeared in the desert wastelands of Arrakis nine years ago. Like their father, the twins possess supernormal abilities--making them valuable to their manipulative aunt Alia, who rules the Empire in the name of House Atreides. Facing treason and rebellion on two fronts, Alia\'s rule is not absolute. The displaced House Corrino is plotting to regain the throne while the fanatical Fremen are being provoked into open revolt by the enigmatic figure known only as The Preacher. Alia believes that by obtaining the secrets of the twins\' prophetic visions, she can maintain control over her dynasty. But Leto and Ghanima have their own plans for their visions--and their destinies....', 'images/children_of_dune.jpg'),
(73, 'Snow Crash', 'Neal Stephenson', '9.99', 'In reality, Hiro Protagonist delivers pizza for Uncle Enzo\'s CosoNostra Pizza Inc., but in the Metaverse he\'s a warrior prince. Plunging headlong into the enigma of a new computer virus that\'s striking down hackers everywhere, he races along the neon-lit streets on a search-and-destroy mission for the shadowy virtual villain threatening to bring about infocalypse. Snow Crash is a mind-altering romp through a future America so bizarre, so outrageous . . . you\'ll recognize it immediately.', 'images/snow_crash.jpg'),
(74, 'Cryptonomicon', 'Neal Stephenson', '10.99', 'Cryptonomicon zooms all over the world, careening conspiratorially back and forth between two time periods—World War II and the present. Our 1940s heroes are the brilliant mathematician Lawrence Waterhouse, crypt analyst extraordinaire, and gung-ho, morphine-addicted marine Bobby Shaftoe. They\'re part of Detachment 2702, an Allied group trying to break Axis communication codes while simultaneously preventing the enemy from figuring out that their codes have been broken. Their job boils down to layer upon layer of deception. Dr. Alan Turing is also a member of 2702, and he explains the unit\'s strange workings to Waterhouse. \"When we want to sink a convoy, we send out an observation plane first... Of course, to observe is not its real duty—we already know exactly where the convoy is. Its real duty is to be observed... Then, when we come round and sink them, the Germans will not find it suspicious.\" All of this secrecy resonates in the present-day story line, in which the grandchildren of the WWII heroes—inimitable programming geek Randy Waterhouse and the lovely and powerful Amy Shaftoe—team up to help create an offshore data haven in Southeast Asia and maybe uncover some gold once destined for Nazi coffers. To top off the paranoiac tone of the book, the mysterious Enoch Root, key member of Detachment 2702 and the Societas Eruditorum, pops up with an unbreakable encryption scheme left over from WWII to befuddle the 1990s protagonists with conspiratorial ties.', 'images/cryptonomicon.jpg'),
(75, 'Seveneves', 'Neal Stephenson', '12.99', 'What would happen if the world were ending? A catastrophic event renders the earth a ticking time bomb. In a feverish race against the inevitable, nations around the globe band together to devise an ambitious plan to ensure the survival of humanity far beyond our atmosphere, in outer space. But the complexities and unpredictability of human nature coupled with unforeseen challenges and dangers threaten the intrepid pioneers, until only a handful of survivors remain . . . Five thousand years later, their progeny—seven distinct races now three billion strong—embark on yet another audacious journey into the unknown . . . to an alien world utterly transformed by cataclysm and time: Earth. A writer of dazzling genius and imaginative vision, Neal Stephenson combines science, philosophy, technology, psychology, and literature in a magnificent work of speculative fiction that offers a portrait of a future that is both extraordinary and eerily recognizable. As he did in Anathem, Cryptonomicon, the Baroque Cycle, and Reamde, Stephenson explores some of our biggest ideas and perplexing challenges in a breathtaking saga that is daring, engrossing, and altogether brilliant.', 'images/seveneves.jpg'),
(76, 'The Three-Body Problem', 'Liu Cixin', '12.99', 'Set against the backdrop of China\'s Cultural Revolution, a secret military project sends signals into space to establish contact with aliens. An alien civilization on the brink of destruction captures the signal and plans to invade Earth. Meanwhile, on Earth, different camps start forming, planning to either welcome the superior beings and help them take over a world seen as corrupt, or to fight against the invasion.', 'images/three_body_problem.jpg'),
(77, 'The Dark Forest', 'Liu Cixin', '11.99', 'This is the second novel in \"Remembrance of Earth\'s Past\", the near-future trilogy written by China\'s multiple-award-winning science fiction author, Cixin Liu. In The Dark Forest, Earth is reeling from the revelation of a coming alien invasion — four centuries in the future. The aliens\' human collaborators have been defeated but the presence of the sophons, the subatomic particles that allow Trisolaris instant access to all human information, means that Earth\'s defense plans are exposed to the enemy. Only the human mind remains a secret. This is the motivation for the Wallfacer Project, a daring plan that grants four men enormous resources to design secret strategies hidden through deceit and misdirection from Earth and Trisolaris alike. Three of the Wallfacers are influential statesmen and scientists but the fourth is a total unknown. Luo Ji, an unambitious Chinese astronomer and sociologist, is baffled by his new status. All he knows is that he\'s the one Wallfacer that Trisolaris wants dead.', 'images/dark_forest.jpg'),
(78, 'Death\'s End', 'Liu Cixin', '11.99', 'With The Three-Body Problem, English-speaking readers got their first chance to experience the multiple-award-winning and bestselling Three-Body Trilogy by China\'s most beloved science fiction author, Cixin Liu. Three-Body was released to great acclaim including coverage in The New York Times and The Wall Street Journal. It was also named a finalist for the Nebula Award, making it the first translated novel to be nominated for a major SF award since Italo Calvino\'s Invisible Cities in 1976. Now this epic trilogy concludes with Death\'s End. Half a century after the Doomsday Battle, the uneasy balance of Dark Forest Deterrence keeps the Trisolaran invaders at bay. Earth enjoys unprecedented prosperity due to the infusion of Trisolaran knowledge. With human science advancing daily and the Trisolarans adopting Earth culture, it seems that the two civilizations will soon be able to co-exist peacefully as equals without the terrible threat of mutually assured annihilation. But the peace has also made humanity complacent. Cheng Xin, an aerospace engineer from the early 21st century, awakens from hibernation in this new age. She brings with her knowledge of a long-forgotten program dating from the beginning of the Trisolar Crisis, and her very presence may upset the delicate balance between two worlds. Will humanity reach for the stars or die in its cradle?', 'images/deaths_end.jpg'),
(79, 'The Grace of Kings', 'Ken Liu', '10.99', 'Wily, charming Kuni Garu, a bandit, and stern, fearless Mata Zyndu, the son of a deposed duke, seem like polar opposites. Yet, in the uprising against the emperor, the two quickly become the best of friends after a series of adventures fighting against vast conscripted armies, silk-draped airships, and shapeshifting gods. Once the emperor has been overthrown, however, they each find themselves the leader of separate factions—two sides with very different ideas about how the world should be run and the meaning of justice.', 'images/grace_of_kings.jpg'),
(80, 'The Wall of Storms', 'Ken Liu', '10.99', 'Kuni Garu, now known as Emperor Ragin, runs the archipelago kingdom of Dara, but struggles to maintain progress while serving the demands of the people and his vision. Then an unexpected invading force from the Lyucu empire in the far distant west comes to the shores of Dara—and chaos results. But Emperor Kuni cannot go and lead his kingdom against the threat himself with his recently healed empire fraying at the seams, so he sends the only people he trusts to be Dara\'s savvy and cunning hopes against the invincible invaders: his children, now grown and ready to make their mark on history.', 'images/wall_of_storms.jpg'),
(81, 'The Veiled Throne', 'Ken Liu', '10.99', 'Princess Théra, once known as Empress Üna of Dara, entrusted the throne to her younger brother in order to journey to Ukyu-Gondé to war with the Lyucu. She has crossed the fabled Wall of Storms with a fleet of advanced warships and ten thousand people. Beset by adversity, Théra and her most trusted companions attempt to overcome every challenge by doing the most interesting thing. But is not letting the past dictate the present always possible or even desirable? In Dara, the Lyucu leadership as well as the surviving Dandelion Court bristle with rivalries as currents of power surge and ebb and perspectives spin and shift. Here, parents and children, teachers and students, Empress and Pékyu, all nurture the seeds of plans that will take years to bloom. Will tradition yield to new justifications for power? Everywhere, the spirit of innovation dances like dandelion seeds on the wind, and the commoners, the forgotten, the ignored begin to engineer new solutions for a new age. Ken Liu returns to the series that draws from a tradition of the great epics of our history from the Aeneid to the Romance on the Three Kingdoms and builds a new tale unsurpassed in its scope and ambition.', 'images/veiled_throne.jpg'),
(82, 'Speaking Bones', 'Ken Liu', '10.99', 'Ukyu-Gondé. Stalked by foes and dogged by betrayal, Princess Théra is pursued across a continent vaster than she could ever have imagined, to the hidden valleys of the World\'s Edge Mountains, into the barrows and subterranean halls of the City of Ghosts, across the ice floes of the far north. She breached the Wall of Storms intent on taking war to the Lyucu homelands, but how do you conquer the unconquerable? Dara. Empress Jia, Prince Phyro and Pékyu Tanvanaki find themselves bound to paths they never would have chosen. Amid atrocity and subterfuge, they will discover that the Courage of Brutes is no substitute for the Grace of Kings, and that little separates the Grace of Kings from the Madness of Tyrants. On both sides of the Wall of Storms, defeat\'s bitter tears mix with the fruits of knowledge new and ancient as two empires bound by blood and bone, by writ and iron, by time and custom, face a whirlwind that threatens to utterly consume them. The teeth, as they say, are on the board.', 'images/speaking_bones.jpg'),
(83, 'Red Rising', 'Pierce Brown', '10.99', 'Darrow is a Red, a member of the lowest caste in the color-coded society of the future. Like his fellow Reds, he works all day, believing that he and his people are making the surface of Mars livable for future generations. Yet he spends his life willingly, knowing that his blood and sweat will one day result in a better world for his children. But Darrow and his kind have been betrayed. Soon he discovers that humanity already reached the surface generations ago. Vast cities and sprawling parks spread across the planet. Darrow—and Reds like him—are nothing more than slaves to a decadent ruling class. Inspired by a longing for justice, and driven by the memory of lost love, Darrow sacrifices everything to infiltrate the legendary Institute, a proving ground for the dominant Gold caste, where the next generation of humanity\'s overlords struggle for power. He will be forced to compete for his life and the very future of civilization against the best and most brutal of Society\'s ruling class. There, he will stop at nothing to bring down his enemies... even if it means he has to become one of them to do so.', 'images/red_rising.jpg'),
(84, 'Golden Son', 'Pierce Brown', '9.99', 'As a Red, Darrow grew up working the mines deep beneath the surface of Mars, enduring backbreaking labor while dreaming of the better future he was building for his descendants. But the Society he faithfully served was built on lies. Darrow\'s kind have been betrayed and denied by their elitist masters, the Golds—and their only path to liberation is revolution. And so Darrow sacrifices himself in the name of the greater good for which Eo, his true love and inspiration, laid down her own life. He becomes a Gold, infiltrating their privileged realm so that he can destroy it from within. A lamb among wolves in a cruel world, Darrow finds friendship, respect, and even love—but also the wrath of powerful rivals. To wage and win the war that will change humankind\'s destiny, Darrow must confront the treachery arrayed against him, overcome his all-too-human desire for retribution—and strive not for violent revolt but a hopeful rebirth. Though the road ahead is fraught with danger and deceit, Darrow must choose to follow Eo\'s principles of love and justice to free his people. He must live for more.', 'images/golden_son.jpg'),
(85, 'Morning Star', 'Pierce Brown', '9.99', 'Darrow would have lived in peace, but his enemies brought him war. The Gold overlords demanded his obedience, hanged his wife, and enslaved his people. But Darrow is determined to fight back. Risking everything to transform himself and breach Gold society, Darrow has battled to survive the cutthroat rivalries that breed Society\'s mightiest warriors, climbed the ranks, and waited patiently to unleash the revolution that will tear the hierarchy apart from within. Finally, the time has come. sBut devotion to honor and hunger for vengeance run deep on both sides. Darrow and his comrades-in-arms face powerful enemies without scruple or mercy. Among them are some Darrow once considered friends. To win, Darrow will need to inspire those shackled in darkness to break their chains, unmake the world their cruel masters have built, and claim a destiny too long denied—and too glorious to surrender.', 'images/morning_star.jpg'),
(86, 'Iron Gold', 'Pierce Brown', '10.99', 'They call him father, liberator, warlord, Reaper. But he feels a boy as he falls toward the pale blue planet, his armor red, his army vast, his heart heavy. It is the tenth year of war and the thirty-second of his life. A decade ago, Darrow was the hero of the revolution he believed would break the chains of the Society. But the Rising has shattered everything: Instead of peace and freedom, it has brought endless war. Now he must risk everything he has fought for on one last desperate mission. Darrow still believes he can save everyone, but can he save himself? And throughout the worlds, other destinies entwine with Darrow\'s to change his fate forever: A young Red girl flees tragedy in her refugee camp and achieves for herself a new life she could never have imagined. An ex-soldier broken by grief is forced to steal the most valuable thing in the galaxy—or pay with his life. And Lysander au Lune, the heir in exile to the sovereign, wanders the stars with his mentor, Cassius, haunted by the loss of the world that Darrow transformed, and dreaming of what will rise from its ashes. Red Rising was the story of the end of one universe, and Iron Gold is the story of the creation of a new one. Witness the beginning of a stunning new saga of tragedy and triumph from masterly New York Times bestselling author Pierce Brown.', 'images/iron_gold.jpg'),
(87, 'Dark Age', 'Pierce Brown', '10.99', 'For a decade Darrow led a revolution against the corrupt color-coded Society. Now, outlawed by the very Republic he founded, he wages a rogue war on Mercury in hopes that he can still salvage the dream of Eo. But as he leaves death and destruction in his wake, is he still the hero who broke the chains? Or will another legend rise to take his place? Lysander au Lune, the heir in exile, has returned to the Core. Determined to bring peace back to mankind at the edge of his sword, he must overcome or unite the treacherous Gold families of the Core and face down Darrow over the skies of war-torn Mercury. But theirs are not the only fates hanging in the balance. On Luna, Mustang, Sovereign of the Republic, campaigns to unite the Republic behind her husband. Beset by political and criminal enemies, can she outwit her opponents in time to save him? Once a Red refugee, young Lyria now stands accused of treason, and her only hope is a desperate escape with unlikely new allies. Abducted by a new threat to the Republic, Pax and Electra, the children of Darrow and Sevro, must trust in Ephraim, a thief, for their salvation—and Ephraim must look to them for his chance at redemption. As alliances shift, break, and re-form—and power is seized, lost, and reclaimed—every player is at risk in a game of conquest that could turn the Rising into a new Dark Age.', 'images/dark_age.jpg'),
(88, 'Light Bringer', 'Pierce Brown', '12.99', '“The measure of a man is not the fear he sows in his enemies. It is the hope he gives his friends.”—Virginia au Augustus The Reaper is a legend, more myth than man: the savior of worlds, the leader of the Rising, the breaker of chains. But the Reaper is also Darrow, born of the red soil of Mars: a husband, a father, a friend. The worlds once needed the Reaper. But now they need Darrow. Because after the dark age will come a new age: of light, of victory, of hope.', 'images/light_bringer.jpg'),
(89, 'Foundation', 'Isaac Asimov', '9.99', 'For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future--to a dark age of ignorance, barbarism, and warfare that will last thirty thousand years. To preserve knowledge and save humankind, Seldon gathers the best minds in the Empire--both scientists and scholars--and brings them to a bleak planet at the edge of the galaxy to serve as a beacon of hope for future generations. He calls his sanctuary the Foundation.', 'images/foundation.jpg'),
(90, 'Foundation and Empire', 'Isaac Asimov', '9.99', 'Foundation and Empire tells the incredible story of a new breed of man who create a new force for galactic government. Thus, the Foundation hurtles into conflict with the decadent, decrepit First Empire. In this struggle for power amid the chaos of the stars, man stands at the threshold of a new, enlightened life which could easily be put aside for the old forces of barbarism. The Foundation novels of Isaac Asimov constitute what is very likely the most famed epic in all of science-fiction.', 'images/foundation_and_empire.jpg'),
(91, 'Second Foundation', 'Isaac Asimov', '9.99', 'So far the Foundation was safe. But there was a hidden Second Foundation to protect the first. The Mule has yet to find it, but he was getting closer all the time. The men of the Foundation sought it, too, to escape from Mule\'s mind control. Only Arkady, a 14 year-old girl seemed to have the answer, or did she...?', 'images/second_foundation.jpg'),
(92, 'The Way of Kings', 'Brandon Sanderson', '12.99', 'Roshar is a world of stone and storms. Uncanny tempests of incredible power sweep across the rocky terrain so frequently that they have shaped ecology and civilization alike. Animals hide in shells, trees pull in branches, and grass retracts into the soilless ground. Cities are built only where the topography offers shelter. It has been centuries since the fall of the ten consecrated orders known as the Knights Radiant, but their Shardblades and Shardplate remain: mystical swords and suits of armor that transform ordinary men into near-invincible warriors. Men trade kingdoms for Shardblades. Wars were fought for them, and won by them. One such war rages on a ruined landscape called the Shattered Plains. There, Kaladin, who traded his medical apprenticeship for a spear to protect his little brother, has been reduced to slavery. In a war that makes no sense, where ten armies fight separately against a single foe, he struggles to save his men and to fathom the leaders who consider them expendable. Brightlord Dalinar Kholin commands one of those other armies. Like his brother, the late king, he is fascinated by an ancient text called The Way of Kings. Troubled by over-powering visions of ancient times and the Knights Radiant, he has begun to doubt his own sanity. Across the ocean, an untried young woman named Shallan seeks to train under an eminent scholar and notorious heretic, Dalinar\'s niece, Jasnah. Though she genuinely loves learning, Shallan\'s motives are less than pure. As she plans a daring theft, her research for Jasnah hints at secrets of the Knights Radiant and the true cause of the war. The result of over ten years of planning, writing, and world-building, The Way of Kings is but the opening movement of the Stormlight Archive, a bold masterpiece in the making.', 'images/way_of_kings.jpg'),
(93, 'Words of Radiance', 'Brandon Sanderson', '13.99', 'Expected by his enemies to die the miserable death of a military slave, Kaladin survived to be given command of the royal bodyguards, a controversial first for a low-status \"darkeyes.\" Now he must protect the king and Dalinar from every common peril as well as the distinctly uncommon threat of the Assassin, all while secretly struggling to master remarkable new powers that are somehow linked to his honorspren, Syl. The Assassin, Szeth, is active again, murdering rulers all over the world of Roshar, using his baffling powers to thwart every bodyguard and elude all pursuers. Among his prime targets is Highprince Dalinar, widely considered the power behind the Alethi throne. His leading role in the war would seem reason enough, but the Assassin\'s master has much deeper motives. Brilliant but troubled Shallan strives along a parallel path. Despite being broken in ways she refuses to acknowledge, she bears a terrible burden: to somehow prevent the return of the legendary Voidbringers and the civilization-ending Desolation that will follow. The secrets she needs can be found at the Shattered Plains, but just arriving there proves more difficult than she could have imagined. Meanwhile, at the heart of the Shattered Plains, the Parshendi are making an epochal decision. Hard pressed by years of Alethi attacks, their numbers ever shrinking, they are convinced by their war leader, Eshonai, to risk everything on a desperate gamble with the very supernatural forces they once fled. The possible consequences for Parshendi and humans alike, indeed, for Roshar itself, are as dangerous as they are incalculable.', 'images/words_of_radiance.jpg'),
(94, 'Oathbringer', 'Brandon Sanderson', '13.99', 'In Oathbringer, the third volume of the New York Times bestselling Stormlight Archive, humanity faces a new Desolation with the return of the Voidbringers, a foe with numbers as great as their thirst for vengeance. Dalinar Kholin\'s Alethi armies won a fleeting victory at a terrible cost: The enemy Parshendi summoned the violent Everstorm, which now sweeps the world with destruction, and in its passing awakens the once peaceful and subservient parshmen to the horror of their millennia-long enslavement by humans. While on a desperate flight to warn his family of the threat, Kaladin Stormblessed must come to grips with the fact that the newly kindled anger of the parshmen may be wholly justified. Nestled in the mountains high above the storms, in the tower city of Urithiru, Shallan Davar investigates the wonders of the ancient stronghold of the Knights Radiant and unearths dark secrets lurking in its depths. And Dalinar realizes that his holy mission to unite his homeland of Alethkar was too narrow in scope. Unless all the nations of Roshar can put aside Dalinar\'s blood-soaked past and stand together--and unless Dalinar himself can confront that past--even the restoration of the Knights Radiant will not prevent the end of civilization.', 'images/oathbringer.jpg'),
(95, 'Rhythm of War', 'Brandon Sanderson', '13.99', 'After forming a coalition of human resistance against the enemy invasion, Dalinar Kholin and his Knights Radiant have spent a year fighting a protracted, brutal war. Neither side has gained an advantage, and the threat of a betrayal by Dalinar\'s crafty ally Taravangian looms over every strategic move. Now, as new technological discoveries by Navani Kholin\'s scholars begin to change the face of the war, the enemy prepares a bold and dangerous operation. The arms race that follows will challenge the very core of the Radiant ideals, and potentially reveal the secrets of the ancient tower that was once the heart of their strength. At the same time that Kaladin Stormblessed must come to grips with his changing role within the Knights Radiant, his Windrunners face their own problem: As more and more deadly enemy Fused awaken to wage war, no more honorspren are willing to bond with humans to increase the number of Radiants. Adolin and Shallan must lead the coalition\'s envoy to the honorspren stronghold of Lasting Integrity and either convince the spren to join the cause against the evil god Odium, or personally face the storm of failure.', 'images/rhythm_of_war.jpg'),
(96, 'The Name of the Wind', 'Patrick Rothfuss', '10.99', 'Told in Kvothe\'s own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen. The intimate narrative of his childhood in a troupe of traveling players, his years spent as a near-feral orphan in a crime-ridden city, his daringly brazen yet successful bid to enter a legendary school of magic, and his life as a fugitive after the murder of a king form a gripping coming-of-age story unrivaled in recent literature. A high-action story written with a poet\'s hand, The Name of the Wind is a masterpiece that will transport readers into the body and mind of a wizard.', 'images/name_of_the_wind.jpg'),
(97, 'The Wise Man\'s Fear', 'Patrick Rothfuss', '12.99', 'My name is Kvothe. I have stolen princesses back from sleeping barrow kings. I burned down the town of Trebon. I have spent the night with Felurian and left with both my sanity and my life. I was expelled from the University at a younger age than most people are allowed in. I tread paths by moonlight that others fear to speak of during day. I have talked to Gods, loved women, and written songs that make the minstrels weep. You may have heard of me. So begins the tale of a hero told from his own point of view — a story unequaled in fantasy literature. Now in The Wise Man\'s Fear, an escalating rivalry with a powerful member of the nobility forces Kvothe to leave the University and seek his fortune abroad. Adrift, penniless, and alone, he travels to Vintas, where he quickly becomes entangled in the politics of courtly society. While attempting to curry favor with a powerful noble, Kvothe uncovers an assassination attempt, comes into conflict with a rival arcanist, and leads a group of mercenaries into the wild, in an attempt to solve the mystery of who (or what) is waylaying travelers on the King\'s Road. All the while, Kvothe searches for answers, attempting to uncover the truth about the mysterious Amyr, the Chandrian, and the death of his parents. Along the way, Kvothe is put on trial by the legendary Adem mercenaries, is forced to reclaim the honor of the Edema Ruh, and travels into the Fae realm. There he meets Felurian, the faerie woman no man can resist, and who no man has ever survived ... until Kvothe. In The Wise Man\'s Fear, Kvothe takes his first steps on the path of the hero and learns how difficult life can be when a man becomes a legend in his own time.', 'images/wise_mans_fear.jpg'),
(98, 'A Wizard of Earthsea', 'Ursula K. Le Guin', '8.99', 'Ged, the greatest sorcerer in all Earthsea, was called Sparrowhawk in his reckless youth. Hungry for power and knowledge, Sparrowhawk tampered with long-held secrets and loosed a terrible shadow upon the world. This is the tale of his testing, how he mastered the mighty words of power, tamed an ancient dragon, and crossed death\'s threshold to restore the balance.', 'images/wizard_of_earthsea.jpg'),
(99, 'The Tombs of Atuan', 'Ursula K. Le Guin', '9.99', 'In this second novel in the Earthsea series, Tenar is chosen as high priestess to the ancient and nameless Powers of the Earth, and everything is taken from her—home, family, possessions, even her name. She is now known only as Arha, the Eaten One, and guards the shadowy, labyrinthine Tombs of Atuan. Then a wizard, Ged Sparrowhawk, comes to steal the Tombs\' greatest hidden treasure, the Ring of Erreth-Akbe. Tenar\'s duty is to protect the Ring, but Ged possesses the light of magic and tales of a world that Tenar has never known. Will Tenar risk everything to escape from the darkness that has become her domain?', 'images/tombs_of_atuan.jpg'),
(100, 'The Farthest Shore', 'Ursula K. Le Guin', '9.99', 'Book Three of Ursula K. Le Guin\'s Earthsea Cycle. Darkness threatens to overtake Earthsea: the world and its wizards are losing their magic. Despite being wearied with age, Ged Sparrowhawk - powerful Archmage, wizard, and dragonlord - embarks on a daring, treacherous journey, accompanied by Enlad\'s young Prince Arren, to discover the reasons behind this devastating pattern of loss. Together they will sail to the farthest reaches of their world -- even beyond the realm of death -- as they seek to restore magic to a land desperately thirsty for it.', 'images/farthest_shore.jpg'),
(101, 'Project Hail Mary', 'Andy Weir', '14.99', 'Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn\'t know that. He can\'t even remember his own name, let alone the nature of his assignment or how to complete it. All he knows is that he\'s been asleep for a very, very long time. And he\'s just been awakened to find himself millions of miles from home, with nothing but two corpses for company. His crewmates dead, his memories fuzzily returning, Ryland realizes that an impossible task now confronts him. Hurtling through space on this tiny ship, it\'s up to him to puzzle out an impossible scientific mystery—and conquer an extinction-level threat to our species. And with the clock ticking down and the nearest human being light-years away, he\'s got to do it all alone. Or does he?', 'images/project_hail_mary.jpg'),
(102, 'The Martian', 'Andy Weir', '12.99', 'Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he\'s sure he\'ll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he\'s alive—and even if he could get word out, his supplies would be gone long before a rescue could arrive. Chances are, though, he won\'t have time to starve to death. The damaged machinery, unforgiving environment, or plain-old “human error” are much more likely to kill him first. But Mark isn\'t ready to give up yet. Drawing on his ingenuity, his engineering skills — and a relentless, dogged refusal to quit — he steadfastly confronts one seemingly insurmountable obstacle after the next. Will his resourcefulness be enough to overcome the impossible odds against him?', 'images/the_martian.jpg'),
(103, 'Neuromancer', 'William Gibson', '8.99', 'Hotwired to the leading edges of art and technology, Neuromancer is a cyberpunk, science fiction masterpiece—a classic that ranks with 1984 and Brave New World as one of the twentieth century\'s most potent visions of the future. The Matrix is a world within the world, a global consensus-hallucination, the representation of every byte of data in cyberspace... Henry Dorsett Case was the sharpest data-thief in the business, until vengeful former employees crippled his nervous system. But now a new and very mysterious employer recruits him for a last-chance run. The target: an unthinkably powerful artificial intelligence orbiting Earth in service of the sinister Tessier-Ashpool business clan. With a dead man riding shotgun and Molly, mirror-eyed street-samurai, to watch his back, Case embarks on an adventure that ups the ante on an entire genre of fiction. The winner of the Hugo, Nebula, and Philip K. Dick Awards, Neuromancer was the first fully-realized glimpse of humankind\'s digital future—a shocking vision that has challenged our assumptions about our technology and ourselves, reinvented the way we speak and think, and forever altered the landscape of our imaginations.', 'images/neuromancer.jpg'),
(104, 'Do Androids Dream of Electric Sheep?', 'Philip K. Dick', '7.99', 'It was January 2021, and Rick Deckard had a license to kill. Somewhere among the hordes of humans out there, lurked several rogue androids. Deckard\'s assignment--find them and then...\"retire\" them. Trouble was, the androids all looked exactly like humans, and they didn\'t want to be found!', 'images/do_androids_dream.jpg'),
(105, 'Rendezvous with Rama', 'Arthur C. Clarke', '7.99', 'At first, only a few things are known about the celestial object that astronomers dub Rama. It is huge, weighing more than ten trillion tons. And it is hurtling through the solar system at an inconceivable speed. Then a space probe confirms the unthinkable: Rama is no natural object. It is, incredibly, an interstellar spacecraft. Space explorers and planet-bound scientists alike prepare for mankind\'s first encounter with alien intelligence. It will kindle their wildest dreams... and fan their darkest fears. For no one knows who the Ramans are or why they have come. And now the moment of rendezvous awaits — just behind a Raman airlock door.', 'images/rendezvous_with_rama.jpg'),
(106, 'The Stars My Destination', 'Alfred Bester', '6.99', 'In this pulse-quickening novel, Alfred Bester imagines a future in which people \"jaunte\" a thousand miles with a single thought, where the rich barricade themselves in labyrinths and protect themselves with radioactive hitmen—and where an inarticulate outcast is the most valuable and dangerous man alive. The Stars My Destination is a classic of technological prophecy and timeless narrative enchantment by an acknowledged master of science fiction.', 'images/stars_my_destination.jpg'),
(107, 'Stranger in a Strange Land', 'Robert A. Heinlein', '9.99', 'Valentine Michael Smith is a human being raised on Mars, newly returned to Earth. Among his people for the first time, he struggles to understand the social mores and prejudices of human nature that are so alien to him, while teaching them his own fundamental beliefs in grokking, watersharing, and love.', 'images/stranger_in_a_strange_land.jpg'),
(108, 'Children of Time', 'Adrian Tchaikovsky', '10.99', 'WHO WILL INHERIT THIS NEW EARTH? The last remnants of the human race left a dying Earth, desperate to find a new home among the stars. Following in the footsteps of their ancestors, they discover the greatest treasure of the past age—a world terraformed and prepared for human life. But all is not right in this new Eden. In the long years since the planet was abandoned, the work of its architects has borne disastrous fruit. The planet is not waiting for them, pristine and unoccupied. New masters have turned it from a refuge into mankind\'s worst nightmare. Now two civilizations are on a collision course, both testing the boundaries of what they will do to survive. As the fate of humanity hangs in the balance, who are the true heirs of this new Earth?', 'images/children_of_time.jpg');
INSERT INTO `products` (`id`, `name`, `author`, `price`, `description`, `image_url`) VALUES
(109, 'Blindsight', 'Peter Watts', '9.99', 'Two months since sixty-five thousand alien objects clenched around the Earth like a luminous fist, screaming to the heavens as the atmosphere burned them to ash. Two months since that moment of brief, bright surveillance by agents unknown. Two months of silence while a world holds its breath. Now some half-derelict space probe, sparking fitfully past Neptune\'s orbit, hears a whisper from the edge of the solar system: a faint signal sweeping the cosmos like a lighthouse beam. Whatever\'s out there isn\'t talking to us. It\'s talking to some distant star, perhaps. Or perhaps to something closer, something en route. So who do you send to force introductions on an intelligence with motives unknown, maybe unknowable? Who do you send to meet the alien when the alien doesn\'t want to meet? You send a linguist with multiple personalities, her brain surgically partitioned into separate, sentient processing cores. You send a biologist so radically interfaced with machinery that he sees X-rays and tastes ultrasound, so compromised by grafts and splices he no longer feels his own flesh. You send a pacifist warrior in the faint hope she won\'t be needed, and a fainter hope she\'ll do any good if she is needed. You send a monster to command them all, an extinct hominid predator once called “vampire,” recalled from the grave with the voodoo of recombinant genetics and the blood of sociopaths. And you send a synthesist – an informational topologist with half his mind gone – as an interface between here and there, a conduit through which the Dead Center might hope to understand the Bleeding Edge. You send them all to the edge of interstellar space, praying you can trust such freaks and retrofits with the fate of a world. You fear they may be more alien than the thing they\'ve been sent to find. But you\'d give anything for that to be true, if you only knew what was waiting for them…', 'images/blindsight.jpg'),
(110, 'The Once and Future King', 'T.H. White', '8.99', 'T.H White\'s masterful retelling of the Arthurian legend is an abiding classic. Here all five volumes that make up the story are published in one volume, as White himself always wished. Exquisite comedy offsets the tragedy of Arthur\'s personal doom as White brings to life the major British epic of all time with brilliance, grandeur, warmth and charm.', 'images/once_and_future_king.jpg'),
(111, 'Jonathan Strange & Mr Norrell', 'Susanna Clarke', '13.99', 'The year is 1806. England is beleaguered by the long war with Napoleon, and centuries have passed since practical magicians faded into the nation\'s past. But scholars of this glorious history discover that one remains: the reclusive Mr Norrell, whose displays of magic send a thrill through the country. Proceeding to London, he raises a beautiful woman from the dead and summons an army of ghostly ships to terrify the French. Yet the cautious, fussy Norrell is challenged by the emergence of another magician: the brilliant novice Jonathan Strange. Young, handsome and daring, Strange is the very antithesis of Norrell. So begins a dangerous battle between these two great men which overwhelms that between England and France. And their own obsessions and secret dabblings with the dark arts are going to cause more trouble than they can imagine.', 'images/jonathan_strange.jpg'),
(112, 'American Gods', 'Neil Gaiman', '11.99', 'Days before his release from prison, Shadow\'s wife, Laura, dies in a mysterious car crash. Numbly, he makes his way back home. On the plane, he encounters the enigmatic Mr Wednesday, who claims to be a refugee from a distant war, a former god and the king of America. Together they embark on a profoundly strange journey across the heart of the USA, whilst all around them a storm of preternatural and epic proportions threatens to break. Scary, gripping and deeply unsettling, American Gods takes a long, hard look into the soul of America. You\'ll be surprised by what - and who - it finds there...', 'images/american_gods.jpg'),
(113, 'The Priory of the Orange Tree', 'Samantha Shannon', '14.99', 'A world divided. A queendom without an heir. An ancient enemy awakens. The House of Berethnet has ruled Inys for a thousand years. Still unwed, Queen Sabran the Ninth must conceive a daughter to protect her realm from destruction--but assassins are getting closer to her door. Ead Duryan is an outsider at court. Though she has risen to the position of lady-in-waiting, she is loyal to a hidden society of mages. Ead keeps a watchful eye on Sabran, secretly protecting her with forbidden magic. Across the dark sea, Tané has trained to be a dragonrider since she was a child, but is forced to make a choice that could see her life unravel. Meanwhile, the divided East and West refuse to parley, and forces of chaos are rising from their sleep.', 'images/priory_of_the_orange_tree.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
  MODIFY `id` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=115;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
